<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Voucher;
use App\Models\VoucherPackage;
use App\Models\CashFlow;
use App\Services\MikrotikService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class VoucherController extends Controller
{
    public function index(Request $request)
    {
        $query = Voucher::with('package');

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }

        if ($request->has('package_id')) {
            $query->where('package_id', $request->package_id);
        }

        if ($request->has('search')) {
            $query->where('code', 'like', "%{$request->search}%");
        }

        return $query->latest()->paginate($request->get('per_page', 10));
    }

    public function generate(Request $request)
    {
        $request->validate([
            'package_id' => 'required|exists:voucher_packages,id',
            'count' => 'required_without:codes|integer|min:1|max:1000',
            'codes' => 'nullable|array',
        ]);

        $package = VoucherPackage::with('router')->find($request->package_id);
        $vouchers = [];
        $codes = $request->codes ?? [];

        // If no codes provided, generate random ones
        if (empty($codes)) {
            for ($i = 0; $i < $request->count; $i++) {
                $codes[] = strtoupper(Str::random(8));
            }
        }

        $service = null;
        if ($package->router_id && $package->mikrotik_profile_name) {
            try {
                $service = new MikrotikService($package->router);
            } catch (\Exception $e) {
                \Log::error('Mikrotik Sync Error: ' . $e->getMessage());
            }
        }

        foreach ($codes as $code) {
            $vouchers[] = [
                'package_id' => $package->id,
                'code' => $code,
                'status' => 'ready',
                'created_by' => auth('api')->id(),
                'created_at' => now(),
                'updated_at' => now(),
            ];

            if ($service) {
                try {
                    $uptime = $package->duration_minutes ? ($package->duration_minutes . 'm') : null;
                    $service->addHotspotUser(
                        $code, // username
                        $code, // password same as username for simple vouchers
                        $package->mikrotik_profile_name,
                        'all',
                        'Generated by Billing System',
                        $uptime
                    );
                } catch (\Exception $e) {
                    \Log::error('Mikrotik Add Hotspot User Error: ' . $e->getMessage());
                }
            }
        }

        Voucher::insert($vouchers);

        return response()->json(['message' => "Successfully generated " . count($codes) . " vouchers."]);
    }

    public function sell(Request $request, Voucher $voucher)
    {
        if ($voucher->status !== 'ready') {
            return response()->json(['error' => 'Voucher is not ready to be sold.'], 400);
        }

        $voucher->update([
            'status' => 'sold',
            'sold_at' => now(),
        ]);

        // Record to CashFlow
        CashFlow::create([
            'transaction_date' => now(),
            'type' => 'income',
            'category' => 'voucher',
            'amount' => $voucher->package->price,
            'description' => "Voucher sale: {$voucher->code}",
            'reference_id' => $voucher->id,
            'created_by' => auth('api')->id(),
        ]);

        return response()->json($voucher->load('package'));
    }

    public function destroy(Voucher $voucher)
    {
        $voucher->delete();
        return response()->json(null, 204);
    }
}
